# Translations template for cinder.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the cinder project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: cinder 7.0.0.0b3.dev341\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-08-27 06:19+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: cinder/context.py:205
msgid "Unable to get internal tenant context: Missing required config parameters."
msgstr ""

#: cinder/quota_utils.py:49
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG volume - "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/quota_utils.py:60 cinder/transfer/api.py:184
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create volume (%(d_consumed)d "
"volumes already consumed)"
msgstr ""

#: cinder/service.py:92
msgid ""
"OSProfiler is enabled.\n"
"It means that person who knows any of hmac_keys that are specified in "
"/etc/cinder/api-paste.ini can trace his requests. \n"
"In real life only operator can read this file so there is no security "
"issue. Note that even if person can trigger profiler, only admin user can"
" retrieve trace information.\n"
"To disable OSprofiler set in cinder.conf:\n"
"[profiler]\n"
"enabled=false"
msgstr ""

#: cinder/service.py:193
#, python-format
msgid ""
"Report interval must be less than service down time. Current config "
"service_down_time: %(service_down_time)s, report_interval for this: "
"service is: %(report_interval)s. Setting global service_down_time to: "
"%(new_down_time)s"
msgstr ""

#: cinder/service.py:261
msgid "Service killed that has no database entry"
msgstr ""

#: cinder/utils.py:998
#, python-format
msgid "Invalid trace flag: %s"
msgstr ""

#: cinder/api/__init__.py:31
msgid ""
"The v1 api is deprecated and will be removed in the Liberty release. You "
"should set enable_v1_api=false and enable_v2_api=true in your cinder.conf"
" file."
msgstr ""

#: cinder/api/extensions.py:276
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: cinder/api/extensions.py:345
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: cinder/api/extensions.py:370
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: cinder/api/openstack/__init__.py:114
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: cinder/backup/api.py:185
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG backup "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/backup/api.py:197
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create backups (%(d_consumed)d "
"backups already consumed)"
msgstr ""

#: cinder/backup/chunkeddriver.py:709
msgid "swift error while listing objects, continuing with delete."
msgstr ""

#: cinder/backup/driver.py:212
msgid ""
"Destination volume type is different from source volume type for an "
"encrypted volume. Encrypted backup restore has failed."
msgstr ""

#: cinder/backup/manager.py:668
#, python-format
msgid ""
"Backup service %(service)s does not support verify. Backup id %(id)s is "
"not verified. Skipping verify."
msgstr ""

#: cinder/backup/drivers/ceph.py:1187
#, python-format
msgid ""
"RBD image for backup %(backup)s of volume %(volume)s not found. Deleting "
"backup metadata."
msgstr ""

#: cinder/common/sqlalchemyutils.py:68
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: cinder/consistencygroup/api.py:103
#, python-format
msgid "Availability zone '%s' is invalid"
msgstr ""

#: cinder/db/sqlalchemy/api.py:222
#, python-format
msgid "Deadlock detected when running '%(func_name)s': Retrying..."
msgstr ""

#: cinder/db/sqlalchemy/api.py:888
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: cinder/image/glance.py:134
msgid ""
"glance_num_retries shouldn't be a negative value. The number of retries "
"will be set to 0 until this iscorrected in the cinder.conf."
msgstr ""

#: cinder/image/image_utils.py:72
msgid "qemu-img is not installed."
msgstr ""

#: cinder/keymgr/conf_key_mgr.py:79
msgid ""
"config option keymgr.fixed_key has not been defined: some operations may "
"fail unexpectedly"
msgstr ""

#: cinder/keymgr/conf_key_mgr.py:135
#, python-format
msgid "Not deleting key %s"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:409
#, python-format
msgid "No weighed hosts found for volume with properties: %s"
msgstr ""

#: cinder/scheduler/host_manager.py:469
#, python-format
msgid "volume service is down. (host: %s)"
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:71
#, python-format
msgid ""
"Insufficient free space for volume creation. Total capacity is "
"%(total).2f on host %(host)s."
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:93
#, python-format
msgid ""
"Insufficient free space for thin provisioning. The ratio of provisioned "
"capacity over total capacity %(provisioned_ratio).2f has exceeded the "
"maximum over subscription ratio %(oversub_ratio).2f on host %(host)s."
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:115
#, python-format
msgid ""
"Insufficient free space for volume creation on host %(host)s (requested /"
" avail): %(requested)s/%(available)s"
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:61
#, python-format
msgid "Error in filtering function '%(function)s' : '%(error)s' :: failing host"
msgstr ""

#: cinder/scheduler/filters/instance_locality_filter.py:97
#, python-format
msgid "Hint \"%s\" dropped because ExtendedServerAttributes not active in Nova."
msgstr ""

#: cinder/scheduler/filters/instance_locality_filter.py:108
#, python-format
msgid ""
"Hint \"%s\" dropped because Nova did not return enough information. "
"Either Nova policy needs to be changed or a privileged account for Nova "
"should be specified in conf."
msgstr ""

#: cinder/scheduler/weights/goodness.py:54
msgid "Goodness function not set :: defaulting to minimal goodness rating of 0"
msgstr ""

#: cinder/scheduler/weights/goodness.py:62
#, python-format
msgid ""
"Error in goodness_function function '%(function)s' : '%(error)s' :: "
"Defaulting to a goodness of 0"
msgstr ""

#: cinder/scheduler/weights/goodness.py:73
#, python-format
msgid ""
"Invalid goodness result.  Result must be between 0 and 100.  Result "
"generated: '%s' :: Defaulting to a goodness of 0"
msgstr ""

#: cinder/transfer/api.py:172 cinder/volume/flows/api/create_volume.py:559
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG volume "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/volume/api.py:715 cinder/volume/api.py:850
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG snapshot "
"(%(d_consumed)dG of %(d_quota)dG already consumed)."
msgstr ""

#: cinder/volume/api.py:727 cinder/volume/api.py:862
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create snapshot (%(d_consumed)d "
"snapshots already consumed)."
msgstr ""

#: cinder/volume/driver.py:480
#, python-format
msgid "Failed to activate volume copy throttling: %(err)s"
msgstr ""

#: cinder/volume/driver.py:748
#, python-format
msgid ""
"Failed terminating the connection of volume %(volume_id)s, but it is "
"acceptable."
msgstr ""

#: cinder/volume/driver.py:1903 cinder/volume/targets/iscsi.py:166
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

#: cinder/volume/manager.py:212
#, python-format
msgid "Driver path %s is deprecated, update your configuration to the new path."
msgstr ""

#: cinder/volume/manager.py:360
#, python-format
msgid "Detected volume stuck in %s(curr_status)s status, setting to ERROR."
msgstr ""

#: cinder/volume/manager.py:376
msgid "Detected snapshot stuck in creating status, setting to ERROR."
msgstr ""

#: cinder/volume/manager.py:1052
#, python-format
msgid "Registration of image volume URI %(uri)s to image %(image_id)s failed."
msgstr ""

#: cinder/volume/manager.py:1125
#, python-format
msgid "Deleting image in unexpected status: %(image_status)s."
msgstr ""

#: cinder/volume/manager.py:1131
msgid "Image delete encountered an error."
msgstr ""

#: cinder/volume/manager.py:1481
#, python-format
msgid ""
"Failed to migrate volume. The destination volume %(vol)s is not deleted "
"since the source volume may have been deleted."
msgstr ""

#: cinder/volume/manager.py:1636
#, python-format
msgid "Update driver status failed: %(config_group)s is uninitialized."
msgstr ""

#: cinder/volume/qos_specs.py:199
#, python-format
msgid "Failed to associate qos specs %(id)s with type: %(vol_type_id)s"
msgstr ""

#: cinder/volume/qos_specs.py:213
#, python-format
msgid "Failed to disassociate qos specs %(id)s with type: %(vol_type_id)s"
msgstr ""

#: cinder/volume/qos_specs.py:227
#, python-format
msgid "Failed to disassociate qos specs %s."
msgstr ""

#: cinder/volume/throttling.py:88
#, python-format
msgid "Failed to setup blkio cgroup to throttle the device '%(device)s'."
msgstr ""

#: cinder/volume/utils.py:275
#, python-format
msgid ""
"Incorrect value error: %(blocksize)s, it may indicate that "
"'volume_dd_blocksize' was configured incorrectly. Fall back to default."
msgstr ""

#: cinder/volume/utils.py:592
#, python-format
msgid "Error encountered translating config_string: %(config_string)s to dict"
msgstr ""

#: cinder/volume/drivers/datera.py:111
msgid ""
"Client cert verification and datera_api_token are deprecated in the "
"Datera driver, and will be removed in the Liberty release. Please set the"
" san_login and san_password in your cinder.conf instead."
msgstr ""

#: cinder/volume/drivers/drbdmanagedrv.py:116
#, python-format
msgid "Got disconnected; trying to reconnect. (%s)"
msgstr ""

#: cinder/volume/drivers/drbdmanagedrv.py:492
#, python-format
msgid "snapshot: %s not found, skipping delete operation"
msgstr ""

#: cinder/volume/drivers/eqlx.py:156
msgid ""
"Configuration options eqlx_use_chap, eqlx_chap_login and "
"eqlx_chap_password are deprecated. Use use_chap_auth, chap_username and "
"chap_password respectively for the same."
msgstr ""

#: cinder/volume/drivers/eqlx.py:170
msgid ""
"Configuration option eqlx_cli_timeout is deprecated and will be removed "
"in M release. Use ssh_conn_timeout instead."
msgstr ""

#: cinder/volume/drivers/eqlx.py:431
#, python-format
msgid "Volume %s was not found while trying to delete it."
msgstr ""

#: cinder/volume/drivers/eqlx.py:546
#, python-format
msgid "Volume %s is not found!, it may have been deleted."
msgstr ""

#: cinder/volume/drivers/glusterfs.py:119
#, python-format
msgid "Exception during unmounting %s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:139
#, python-format
msgid "Failed to refresh mounts, reason=%s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:241 cinder/volume/drivers/quobyte.py:189
#: cinder/volume/drivers/remotefs.py:284
#, python-format
msgid "Volume %s does not have provider_location specified, skipping"
msgstr ""

#: cinder/volume/drivers/hgst.py:344
msgid "Unable to poll cluster free space."
msgstr ""

#: cinder/volume/drivers/hgst.py:410
#, python-format
msgid "Unable to delete space %(space)s"
msgstr ""

#: cinder/volume/drivers/hgst.py:415
msgid "Attempted to delete a space that's not there."
msgstr ""

#: cinder/volume/drivers/lvm.py:176
#, python-format
msgid "Unable to update stats on non-initialized Volume Group: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:417 cinder/volume/drivers/srb.py:770
#, python-format
msgid "snapshot: %s not found, skipping delete operations"
msgstr ""

#: cinder/volume/drivers/lvm.py:723
msgid ""
"LVMISCSIDriver is deprecated, you should now just use LVMVolumeDriver and"
" specify iscsi_helper for the target driver you wish to use."
msgstr ""

#: cinder/volume/drivers/lvm.py:740
msgid ""
"LVMISERDriver is deprecated, you should now just use LVMVolumeDriver and "
"specify iscsi_helper for the target driver you wish to use. In order to "
"enable iser, please set iscsi_protocol with the value iser."
msgstr ""

#: cinder/volume/drivers/nfs.py:344 cinder/volume/drivers/remotefs.py:571
#, python-format
msgid ""
"The NAS file permissions mode will be 666 (allowing other/world read & "
"write access). This is considered an insecure NAS environment. Please see"
" %s for information on a secure NFS configuration."
msgstr ""

#: cinder/volume/drivers/nfs.py:365 cinder/volume/drivers/remotefs.py:564
#, python-format
msgid ""
"The NAS file operations will be run as root: allowing root level access "
"at the storage backend. This is considered an insecure NAS environment. "
"Please see %s for information on a secure NAS configuration."
msgstr ""

#: cinder/volume/drivers/pure.py:187
#, python-format
msgid "Volume deletion failed with message: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:266
#, python-format
msgid "Purity host deletion failed: %(msg)s."
msgstr ""

#: cinder/volume/drivers/pure.py:411
#, python-format
msgid "Unable to delete Protection Group: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:476
#, python-format
msgid "Unable to delete Protection Group Snapshot: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:583
#, python-format
msgid "Volume unmanage was unable to rename the volume, error message: %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:336
#, python-format
msgid "Exception during mounting %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:396
#, python-format
msgid "Failed to unmount previous mount: %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:400
#, python-format
msgid "Unknown error occurred while checking mount point: %s Trying to continue."
msgstr ""

#: cinder/volume/drivers/quobyte.py:419
#, python-format
msgid "%s is already mounted"
msgstr ""

#: cinder/volume/drivers/quobyte.py:438
#, python-format
msgid "Volume is not writable. Please broaden the file permissions. Mount: %s"
msgstr ""

#: cinder/volume/drivers/rbd.py:187
msgid "flush() not supported in this version of librbd"
msgstr ""

#: cinder/volume/drivers/rbd.py:398
msgid "Unable to get rados pool stats."
msgstr ""

#: cinder/volume/drivers/rbd.py:903
msgid "volume_tmp_dir is now deprecated, please use image_conversion_dir."
msgstr ""

#: cinder/volume/drivers/remotefs.py:369
#, python-format
msgid "%(path)s is being set with open permissions: %(perm)s"
msgstr ""

#: cinder/volume/drivers/remotefs.py:981
#, python-format
msgid "No backing file found for %s, allowing snapshot to be deleted."
msgstr ""

#: cinder/volume/drivers/smbfs.py:230 cinder/volume/drivers/ibm/ibmnas.py:291
#, python-format
msgid "Volume %s does not have provider_location specified, skipping."
msgstr ""

#: cinder/volume/drivers/solidfire.py:523
#, python-format
msgid "More than one valid preset was detected, using %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:782
msgid "Requested image is not accessible by current Tenant."
msgstr ""

#: cinder/volume/drivers/srb.py:90
#, python-format
msgid "Retrying failed call to %(func)s, attempt %(attempt)i."
msgstr ""

#: cinder/volume/drivers/srb.py:368
#, python-format
msgid "%s is not an accepted REST server IP address"
msgstr ""

#: cinder/volume/drivers/srb.py:377
msgid "Configuration variable srb_base_urls not set or empty."
msgstr ""

#: cinder/volume/drivers/srb.py:627
#, python-format
msgid "All attempts to recover failed detach of %(volume)s failed."
msgstr ""

#: cinder/volume/drivers/srb.py:687
#, python-format
msgid "Removed volume group %s still appears in vgs."
msgstr ""

#: cinder/volume/drivers/srb.py:886
#, python-format
msgid "Volume %r not found while trying to remove."
msgstr ""

#: cinder/volume/drivers/srb.py:889
#, python-format
msgid "Error while removing export: %r"
msgstr ""

#: cinder/volume/drivers/tintri.py:326
#, python-format
msgid "Exception while creating image %(image_id)s snapshot. Exception: %(exc)s"
msgstr ""

#: cinder/volume/drivers/tintri.py:351
#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:445
#, python-format
msgid "Exception during deleting %s"
msgstr ""

#: cinder/volume/drivers/tintri.py:360
#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:723
#, python-format
msgid "Destination %s already exists."
msgstr ""

#: cinder/volume/drivers/tintri.py:368
#, python-format
msgid "Exception moving file %(src)s. Message: %(e)s"
msgstr ""

#: cinder/volume/drivers/tintri.py:428
#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:504
#, python-format
msgid "Unexpected exception during image cloning in share %s"
msgstr ""

#: cinder/volume/drivers/tintri.py:534
msgid "Unexpected exception while listing used share."
msgstr ""

#: cinder/volume/drivers/xio.py:465
#, python-format
msgid "IOnetworks GET failed (%d)"
msgstr ""

#: cinder/volume/drivers/xio.py:590
#, python-format
msgid "Could not get status for %(name)s (%(status)d)."
msgstr ""

#: cinder/volume/drivers/xio.py:597
msgid "No volume node in XML content."
msgstr ""

#: cinder/volume/drivers/xio.py:604
#, python-format
msgid "No status payload for volume %s."
msgstr ""

#: cinder/volume/drivers/xio.py:692
#, python-format
msgid "Volume %(name)s already presented (%(status)d)!"
msgstr ""

#: cinder/volume/drivers/xio.py:961
#, python-format
msgid "Could not get pool information (%s)!"
msgstr ""

#: cinder/volume/drivers/xio.py:1197
#, python-format
msgid "%s not found!"
msgstr ""

#: cinder/volume/drivers/xio.py:1208
#, python-format
msgid "DELETE call failed for %s!"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:377
#, python-format
msgid "Logout error: %(code)d %(reason)s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:567
#, python-format
msgid "Volume initialization failure. (%s)"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:626
#: cinder/volume/drivers/dell/dell_storagecenter_api.py:2174
#, python-format
msgid "Unable to create folder %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:775
#, python-format
msgid "delete_volume: unable to find volume %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:852
#, python-format
msgid "ScServerOperatingSystem GetList return: %(code)d %(reason)s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1161
msgid "Inconsistent Luns."
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1540
#, python-format
msgid "Unable to create snapshot %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1578
#: cinder/volume/drivers/dell/dell_storagecenter_api.py:2074
#, python-format
msgid "Unable to find snapshot %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_common.py:188
#, python-format
msgid "Unable to locate volume:%s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_common.py:661
#, python-format
msgid ""
"Unable to retype Storage Profile, expected to receive current and "
"requested storagetype:storageprofile values. Value received: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:676
msgid ""
"The VMAX plugin only supports Retype. If a pool based migration is "
"necessary this will happen on a Retype From the command line: cinder "
"--os-volume-api-version 2 retype <volumeId> <volumeType> --migration-"
"policy on-demand"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:713
#, python-format
msgid ""
"Failed to migrate: %(volumeName)s from default source storage group for "
"FAST policy: %(sourceFastPolicyName)s. Attempting cleanup... "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:741
#, python-format
msgid ""
"Attempting a rollback of: %(volumeName)s to original pool "
"%(sourcePoolInstanceName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:773
#, python-format
msgid "_migrate_rollback on : %(volumeName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:809
#, python-format
msgid "_migrate_cleanup on : %(volumeName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:1006
#, python-format
msgid ""
"The volume: %(volumename)s was not first part of the default storage "
"group for FAST policy %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:1099
#, python-format
msgid "Volume: %(volumeName)s is not currently belonging to any storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:2127
#, python-format
msgid ""
"Pre check for deletion. Volume: %(volumeName)s is part of a storage "
"group. Attempting removal from %(storageGroupInstanceNames)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:2993
#, python-format
msgid "Volume : %(volumeName)s is not currently belonging to any storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3266
#, python-format
msgid ""
"The volume: %(volumename)s. was not first part of the default storage "
"group for FAST policy %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3707
#, python-format
msgid ""
"Clone failed on V3. Cleaning up the target volume. Clone name: "
"%(cloneName)s "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3918
#, python-format
msgid "FAST is enabled. Policy: %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:140
#, python-format
msgid "Volume: %(volumeName)s Does not belong to storage group %(defaultSgName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:411
msgid "Unable to get storage tiers from tier policy rule."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fc.py:235
#, python-format
msgid "Volume %(volume)s is not in any masking view."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:107
#, python-format
msgid ""
"Volume: %(volumeName)s Does not belong to storage storage group "
"%(defaultSgGroupName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:500
#, python-format
msgid "Volume: %(volumeName)s is already part of storage group %(sgGroupName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1081
#: cinder/volume/drivers/emc/emc_vmax_masking.py:1348
#, python-format
msgid "Unable to find Masking view: %(view)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1250
#, python-format
msgid ""
"No storage group found. Performing rollback on Volume: %(volumeName)s To "
"return it to the default storage group for FAST policy "
"%(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1630
#, python-format
msgid ""
"Volume %(volumeName)s was not first part of the default storage group for"
" the FAST Policy."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1784
#, python-format
msgid ""
"Only one volume remains in storage group %(sgname)s. Driver will attempt "
"cleanup."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1790
#, python-format
msgid "Unable to get masking view %(maskingView)s from storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2105
#, python-format
msgid "No target ports found in masking view %(maskingView)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2159
#: cinder/volume/drivers/emc/emc_vmax_masking.py:2178
#, python-format
msgid "No port group found in masking view %(mv)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_provision_v3.py:624
#, python-format
msgid ""
"Remaining capacity %(remainingCapacityGb)s GBs is determined from SRP "
"pool capacity and not the SLO capacity. Performance may not be what you "
"expect."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1220
#, python-format
msgid "Storage sync name not found for target %(target)s on %(storageSystem)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1261
#, python-format
msgid ""
"Group sync name not found for target group %(target)s on "
"%(storageSystem)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1740
#, python-format
msgid ""
"CreateStorageHardwareID failed. initiator: %(initiator)s, rc=%(rc)d, "
"ret=%(ret)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1760
msgid "Cannot determine the hardware type."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:362
msgid "san_secondary_ip is configured as the same value as san_ip."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:496
#, python-format
msgid "LUN already exists, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:549
#, python-format
msgid "LUN is already deleted, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:622
#, python-format
msgid "LUN %(name)s is already expanded. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:673
#, python-format
msgid "Consistency group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:765
#, python-format
msgid "CG %(cg_name)s does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:769
#, python-format
msgid "CG %(cg_name)s is deleting. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:793
#, python-format
msgid "Cgsnapshot name %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:808
#, python-format
msgid "Snapshot %(name)s for consistency group does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:827
#: cinder/volume/drivers/emc/emc_vnx_cli.py:847
#, python-format
msgid "Snapshot %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:864
#, python-format
msgid "Snapshot %(name)s may deleted already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:871
#, python-format
msgid "Snapshot %(name)s is in use, retry. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:898
#, python-format
msgid "Mount point %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:925
#, python-format
msgid ""
"Snapshot %(snapname)s is attached to snapshot mount point %(mpname)s "
"already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:945
#, python-format
msgid "The specified Snapshot mount point %s is not currently attached."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:977
#, python-format
msgid ""
"Migration command may get network timeout. Double check whether migration"
" in fact started successfully. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:989
#, python-format
msgid "Start migration failed. Message: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:992
#, python-format
msgid "Delete temp LUN after migration start failed. LUN: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1134
#, python-format
msgid "Storage group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1150
#, python-format
msgid ""
"Storage group %(name)s doesn't exist, may have already been deleted. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1180
#, python-format
msgid ""
"Host %(host)s has already disconnected from storage group %(sgname)s. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1217
#, python-format
msgid "HLU %(hlu)s has already been removed from %(sgname)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1376
msgid "No array serial number returned, set as unknown."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1410
#, python-format
msgid "Storage Group %s is not found."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1519
#, python-format
msgid ""
"Invalid iSCSI port %(sp)s-%(port)s-%(vlan)s found in io_port_list, will "
"be ignored."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1588
#, python-format
msgid "See unavailable iSCSI target: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1807
msgid ""
"destroy_empty_storage_group: True. Empty storage group will be deleted "
"after volume is detached."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1828
msgid "force_delete_lun_in_storagegroup=True"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1835
msgid ""
"ignore_pool_full_threshold: True. LUN creation will still be forced even "
"if the pool full threshold is exceeded."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1855
#, python-format
msgid ""
"The following specified storage pools do not exist: %(unexist)s. This "
"host will only manage the storage pools: %(exist)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2014
msgid ""
"Extra spec key 'storagetype:pool' is obsoleted since driver version "
"5.1.0. This key will be ignored."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2049
msgid ""
"Both 'storagetype:prvosioning' and 'provisioning:type' are set in the "
"extra specs, the value of 'provisioning:type' will be used. The key "
"'storagetype:provisioning' may be deprecated in the next release."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2058
msgid ""
"Extra spec key 'storagetype:provisioning' may be deprecated in the next "
"release. It is recommended to use extra spec key 'provisioning:type' "
"instead."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2111
#, python-format
msgid ""
"LUN corresponding to %s is still in some Storage Groups.Try to bring the "
"LUN out of Storage Groups and retry the deletion."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2144
#, python-format
msgid "LUN %(name)s is not ready for extension: %(out)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2165
msgid ""
"Failed to get target_pool_name and target_array_serial. 'location_info' "
"is not in host['capabilities']."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2178
msgid "Error on parsing target_pool_name/target_array_serial."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2192
msgid ""
"Didn't get the pool information of the host %(s). Storage assisted "
"Migration is not supported. The host may be using a legacy driver."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2301
#: cinder/volume/drivers/huawei/huawei_driver.py:770
msgid "Storage-assisted migration failed during retype."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2363
#, python-format
msgid "Storage Pool '%(pool)s' is '%(state)s'."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2373
#, python-format
msgid ""
"Maximum number of Pool LUNs, %s, have been created. No more LUN creation "
"can be done."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2477
#, python-format
msgid "LUN %(name)s is not ready for snapshot: %(out)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2740
#, python-format
msgid "LUN with id %(remove_id)s is not present in cg %(cg_name)s, skip it."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2834
#, python-format
msgid "Storage Group %s is not found. Create it."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2899
#, python-format
msgid "Failed to register %(itor)s to SP%(sp)s port %(portid)s because: %(msg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3016
#, python-format
msgid "Failed to extract initiators of %s, so ignore deregistration operation."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3023
#, python-format
msgid "Failed to deregister %(itor)s because: %(msg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3284
#, python-format
msgid "Storage Group %s is not found. terminate_connection() is unnecessary."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3293
#, python-format
msgid "Volume %(vol)s was not in Storage Group %(sg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3315
#, python-format
msgid "Failed to destroy Storage Group %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3321
#, python-format
msgid "Fail to connect host %(host)s back to storage group %(sg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3498
#, python-format
msgid ""
"Delete the temporary cgsnapshot %(name)s failed. This temporary "
"cgsnapshot can be deleted manually. Consistency group %(cg)s is created "
"successfully from cgsnapshot %(cgsnapshot)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3534
#, python-format
msgid ""
"The source volume is a legacy volume. Create volume in the pool where the"
" source volume %s is created."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3609
#, python-format
msgid "CreateSMPTask.revert: delete mount point %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3629
#, python-format
msgid "AttachSnapTask.revert: detach mount point %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3667
#, python-format
msgid "CreateDestLunTask.revert: delete temp lun %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3734
#, python-format
msgid "CreateSnapshotTask.revert: delete temp cgsnapshot %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3739
#, python-format
msgid "CreateSnapshotTask.revert: delete temp snapshot %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3761
#, python-format
msgid ""
"CopySnapshotTask.revert: delete the copied snapshot %(new_name)s of "
"%(source_name)s."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:132
msgid "No storage pool name or id was found."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:154
msgid "No protection domain name or id was specified in configuration."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:175
msgid "Verify certificate is not set, using default of False."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:617
#: cinder/volume/drivers/emc/scaleio.py:672
#, python-format
msgid ""
"Ignoring error in delete volume %s: volume not found due to force delete "
"settings."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:919
#, python-format
msgid ""
"scaleIO volume %(vol)s not yet found (no directory /dev/disk/by-id yet). "
"Try number: %(tries)d."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:937
#, python-format
msgid "scaleIO volume %(vol)s not yet found. Try number: %(tries)d."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:1030
#, python-format
msgid "Ignoring error mapping volume %s: volume already mapped."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:1089
#, python-format
msgid "Ignoring error unmapping volume %s: volume not mapped."
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:139
#, python-format
msgid "object %(key)s of type %(typ)s not found, %(err_msg)s"
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:516
msgid "terminate_connection: lun map not found"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_common.py:417
#: cinder/volume/drivers/hitachi/hbsd_common.py:423
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1344
#, python-format
msgid "Failed to restart horcm: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_fc.py:181
#, python-format
msgid "Failed to add host group: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_horcm.py:853
#, python-format
msgid "Failed to discard zero page: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1322
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1331
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1338
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1362
#, python-format
msgid "Failed to create pair: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_snm2.py:145
#, python-format
msgid "ldev(%(ldev)d) is already mapped (hlun: %(hlu)d)"
msgstr ""

#: cinder/volume/drivers/hitachi/hnas_backend.py:267
#, python-format
msgid "get_evs: %(out)s -- No find for %(fsid)s"
msgstr ""

#: cinder/volume/drivers/hitachi/hnas_backend.py:302
#, python-format
msgid "get_fsid: %(out)s -- No info for %(fslabel)s"
msgstr ""

#: cinder/volume/drivers/hitachi/hnas_iscsi.py:716
msgid "terminate_conn: provider location empty."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:150
#, python-format
msgid "Can't find lun %s on the array."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:464
#, python-format
msgid "Failure deleting the snapshot %(snapshot_id)s of volume %(volume_id)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:530
#: cinder/volume/drivers/huawei/huawei_driver.py:532
msgid "Can't find snapshot on the array."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:711
#: cinder/volume/drivers/huawei/huawei_driver.py:988
msgid "Can't find lun on the array."
msgstr ""

#: cinder/volume/drivers/huawei/rest_client.py:1177
#: cinder/volume/drivers/huawei/rest_client.py:1186
msgid "Can't find target iqn from rest."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:316
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:353
#, python-format
msgid "Failed to run command: %s."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:757
msgid "_remove_device: invalid properties or device."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:811
#, python-format
msgid ""
"_unmap_vdisk_from_host: No mapping of volume %(vol_name)s to any host "
"found."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:817
#, python-format
msgid ""
"_unmap_vdisk_from_host: Multiple mappings of volume %(vdisk_name)s found,"
" no host specified."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_fc.py:214
#: cinder/volume/drivers/ibm/flashsystem_iscsi.py:186
#, python-format
msgid "_get_vdisk_map_properties: Did not find a preferred node for vdisk %s."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:189
msgid ""
"The option storwize_svc_npiv_compatibility_mode will be deprecated and "
"not used. It will be removed in the M release."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:384
msgid "CHAP secret exists for host but CHAP is disabled."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:429
#, python-format
msgid "initialize_connection: Did not find a preferred node for volume %s."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:486
#, python-format
msgid ""
"Unable to find a preferred node match for node %(node)s in the list of "
"available WWPNs on %(host)s. Using first available."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:802
#, python-format
msgid "Volume %s does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/helpers.py:348
#, python-format
msgid "unmap_vol_from_host: No mapping of volume %(vol_name)s to any host found."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/helpers.py:354
#, python-format
msgid ""
"unmap_vol_from_host: Multiple mappings of volume %(vol_name)s found, no "
"host specified."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/helpers.py:366
#, python-format
msgid ""
"unmap_vol_from_host: No mapping of volume %(vol_name)s to host %(host)s "
"found."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:90
msgid "The MCS Channel is grouped."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:94
msgid "No mapping."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:102
msgid "IQN already existed."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:107
msgid "IQN has been used to create map."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:108
msgid "No such host alias name."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:842
#, python-format
msgid "Volume %(volume_id)s already deleted."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:853
#, python-format
msgid "Volume still %(status)s Cannot delete volume."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1158
msgid "Failed to get Raid Snapshot ID and did not store in snapshot."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1171
#, python-format
msgid "Snapshot still %(status)s Cannot delete snapshot."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1630
msgid "Failed to get target pool id."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1867
#, python-format
msgid "Volume %(volume_id)s cannot be retyped during attachment."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1874
#, python-format
msgid "Volume %(volume_id)s cannot be retyped because it has snapshot."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1897
#, python-format
msgid "The provisioning: %(provisioning)s is not valid."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:65
msgid ""
"It is not the recommended way to use drivers by NetApp. Please use "
"NetAppDriver to achieve the functionality."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:140
#, python-format
msgid "Extra spec %(old)s is obsolete.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:145
#, python-format
msgid "Extra spec %(old)s is deprecated.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:132
#, python-format
msgid "Could not determine root volume name on %s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:322
msgid "Volume refresh job already running. Returning..."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:329
#, python-format
msgid "Error refreshing volume info. Message: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_base.py:208
#, python-format
msgid "No entry in LUN table for volume/snapshot %(name)s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_base.py:336
#, python-format
msgid ""
"LUN misalignment may occur for current initiator group %(ig_nm)s) with "
"host OS type %(ig_os)s. Please configure initiator group manually "
"according to the type of the host OS."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:318
#, python-format
msgid ""
"Exception while registering image %(image_id)s in cache. Exception: "
"%(exc)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:387
#, python-format
msgid "Exception during cache cleaning %(share)s. Message - %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:598
msgid "Discover file retries exhausted."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:656
msgid "Unexpected exception while short listing used share."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:731
#, python-format
msgid "Exception moving file %(src)s. Message - %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_cmode.py:223
msgid "No shares found hence skipping ssc refresh."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:519
msgid "ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:531
msgid "refresh stale ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:636
#, python-format
msgid ""
"The user does not have access or sufficient privileges to use all netapp "
"APIs. The following extra_specs will fail or be ignored: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_7mode.py:131
#, python-format
msgid "Error finding LUNs for volume %s. Verify volume exists."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:119
#, python-format
msgid "Error mapping LUN. Code :%(code)s, Message: %(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:132
#, python-format
msgid "Error unmapping LUN. Code :%(code)s, Message: %(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:340
#, python-format
msgid "Failed to invoke ems. Message : %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_cmode.py:375
#, python-format
msgid "Rename failure in cleanup of cDOT QOS policy group %(name)s: %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:163
#, python-format
msgid ""
"Production use of \"%(backend)s\" backend requires the Cinder controller "
"to have multipathing properly set up and the configuration option "
"\"%(mpflag)s\" to be set to \"True\"."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:412
msgid "Snapshot volume not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:453
#, python-format
msgid "Failure deleting job %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:456
#, python-format
msgid "Volume copy job for src vol %s not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:471
#, python-format
msgid "Failure deleting temp snapshot %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:480
#, python-format
msgid "Volume %s already deleted."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:507
#, python-format
msgid "Snapshot %s already deleted."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:773
#, python-format
msgid "Unable to update host type for host with label %(l)s. %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:778
#, python-format
msgid "Message - %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:956
#, python-format
msgid "No storage pool found with available capacity %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:987
msgid "Returning as clean tmp vol job already running."
msgstr ""

#: cinder/volume/drivers/prophetstor/dpl_iscsi.py:154
#, python-format
msgid "Cannot get volume status %(exc)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1255
#, python-format
msgid "Flexvisor failed to delete volume %(id)s from the group %(vgid)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1260
#, python-format
msgid ""
"Flexvisor failed to delete volume %(id)s from group %(vgid)s due to "
"%(status)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1429
#, python-format
msgid "Failed to query pool %(id)s status %(ret)d."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:273
#, python-format
msgid ""
"getCPGStatData requires hp3parclient version '%(getcpgstatdata_version)s'"
" version '%(version)s' is installed."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:332
#, python-format
msgid ""
"srstatld requires WSAPI version '%(srstatld_version)s' version "
"'%(version)s' is installed."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:429
#, python-format
msgid "Virtual Volume Set '%s' doesn't exist on array."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:529
#: cinder/volume/drivers/san/hp/hp_3par_common.py:1996
#, python-format
msgid "Delete Snapshot id not found. Removing from cinder: %(id)s Ex: %(msg)s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:626
#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:737
#, python-format
msgid "Failed to manage virtual volume %(disp)s due to error during retype."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:1060
#, python-format
msgid "3PAR vlun for volume %(name)s not found on host %(host)s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:1351
msgid ""
"'hp3par:cpg' is not supported as an extra spec in a volume type.  CPG's "
"are chosen by the cinder scheduler, as a pool, from the cinder.conf entry"
" 'hp3par_cpg', which can be a list of CPGs."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:1655
#, python-format
msgid "Delete volume id not found. Removing from cinder: %(id)s Ex: %(msg)s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:176
#, python-format
msgid "Invalid IP address format '%s'"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:209
#, python-format
msgid ""
"Found invalid iSCSI IP address(s) in configuration option(s) "
"hp3par_iscsi_ips or iscsi_ip_address '%s.'"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:342
#, python-format
msgid ""
"iSCSI IP: '%s' was not found in hp3par_iscsi_ips list defined in "
"cinder.conf."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:380
msgid "Least busy iSCSI port not found, using first iSCSI port in list."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:533
msgid ""
"Host exists without CHAP credentials set and has iSCSI attachments but "
"CHAP is enabled. Updating host with new CHAP credentials."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:565
msgid "Host has no CHAP key, but CHAP is enabled."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:569
msgid "No host or VLUNs exist. Generating new CHAP key."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:598
msgid "Non-iSCSI VLUN detected."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:602
msgid "No VLUN contained CHAP credentials. Generating new CHAP key."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_cliq_proxy.py:86
msgid ""
"The HPLeftHandISCSIDriver CLIQ driver has been DEPRECATED as of the "
"2015.2 release. This driver will be removed in the 2016.1 release. Please"
" use the HPLeftHandISCSIDriver REST based driver instead."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:170
#, python-format
msgid ""
"HPLeftHand API is version %(current)s. A minimum version of %(min)s is "
"needed for manage/unmanage support."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:489
#, python-format
msgid "CHAP secret exists for host %s but CHAP is disabled"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:492
#, python-format
msgid "CHAP is enabled, but server secret not configured on server %s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:566
#, python-format
msgid "%s"
msgstr ""

#: cinder/volume/drivers/violin/v6000_common.py:192
#, python-format
msgid "Lun create for %s failed!"
msgstr ""

#: cinder/volume/drivers/violin/v6000_common.py:217
#, python-format
msgid "Lun %s has dependent snapshots, skipping."
msgstr ""

#: cinder/volume/drivers/violin/v6000_fcp.py:445
#: cinder/volume/drivers/violin/v6000_iscsi.py:464
msgid "Failed to receive update for total_gb stat!"
msgstr ""

#: cinder/volume/drivers/violin/v6000_fcp.py:452
#: cinder/volume/drivers/violin/v6000_iscsi.py:471
msgid "Failed to receive update for free_gb stat!"
msgstr ""

#: cinder/volume/drivers/vmware/datastore.py:226
#, python-format
msgid "Unable to fetch datastores connected to host %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:220
msgid ""
"The VMware ESX VMDK driver is now deprecated and will be removed in the "
"Juno release. The VMware vCenter VMDK driver will remain and continue to "
"be supported."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:570
#, python-format
msgid "Trying to boot from an empty volume: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:843
#, python-format
msgid "Error occurred while deleting temporary disk: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:974
#, python-format
msgid "Error occurred while deleting descriptor: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1007
#, python-format
msgid "Error occurred while deleting backing: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1373
#, python-format
msgid "Volume: %s is in use, can't retype."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1442
#, python-format
msgid ""
"There are no datastores matching new requirements; can't retype volume: "
"%s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1497
#, python-format
msgid ""
"Changing backing: %(backing)s name from %(new_name)s to %(old_name)s "
"failed."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1744
#, python-format
msgid ""
"Cannot undo volume rename; old name was %(old_name)s and new name is "
"%(new_name)s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1870
#, python-format
msgid ""
"Running Cinder with a VMware vCenter version less than %(min_version)s is"
" deprecated. The minimum required version of vCenter server will be "
"raised to %(min_version)s in the 8.0.0 release."
msgstr ""

#: cinder/volume/drivers/zfssa/zfssaiscsi.py:156
msgid "zfssa_initiator_config not found. Using deprecated configuration options."
msgstr ""

#: cinder/volume/drivers/zfssa/zfssaiscsi.py:161
#, python-format
msgid ""
"zfssa_initiator: %(ini)s wont be used on zfssa_initiator_group= "
"%(inigrp)s."
msgstr ""

#: cinder/volume/flows/api/create_volume.py:336
msgid "Volume type will be changed to be the same as the source volume."
msgstr ""

#: cinder/volume/flows/api/create_volume.py:572
#, python-format
msgid ""
"Quota %(s_name)s exceeded for %(s_pid)s, tried to create volume "
"(%(d_consumed)d volume(s) already consumed)."
msgstr ""

#: cinder/volume/targets/cxt.py:159 cinder/volume/targets/tgt.py:195
#, python-format
msgid "Persistence file already exists for volume, found file at: %s"
msgstr ""

#: cinder/volume/targets/cxt.py:224 cinder/volume/targets/tgt.py:286
#, python-format
msgid "Volume path %s does not exist, nothing to remove."
msgstr ""

#: cinder/volume/targets/iet.py:113
#, python-format
msgid ""
"Failed to find CHAP auth from config for %(vol_id)s. Config file %(conf)s"
" does not exist."
msgstr ""

#: cinder/volume/targets/iet.py:227
#, python-format
msgid ""
"Failed to update %(conf)s for volume id %(vol_id)s after removing iscsi "
"target. %(conf)s does not exist."
msgstr ""

#: cinder/volume/targets/iscsi.py:47
#, python-format
msgid ""
"The option %s has been deprecated and no longer has any effect. It will "
"be removed in the Liberty release."
msgstr ""

#: cinder/volume/targets/iser.py:28
msgid ""
"ISERTgtAdm is deprecated, you should now just use LVMVolumeDriver and "
"specify iscsi_helper for the target driver you wish to use. In order to "
"enable iser, please set iscsi_protocol=iser with lioadm or tgtadm target "
"helpers."
msgstr ""

#: cinder/volume/targets/lio.py:92
#, python-format
msgid ""
"Failed to save iscsi LIO configuration when modifying volume id: "
"%(vol_id)s."
msgstr ""

#: cinder/volume/targets/tgt.py:85
msgid "Attempting recreate of backing lun..."
msgstr ""

#: cinder/volume/targets/tgt.py:223
#, python-format
msgid "Could not create target because it already exists for volume: %s"
msgstr ""

#: cinder/volume/targets/tgt.py:308
#, python-format
msgid ""
"Failed target removal because target or ACL's couldn't be found for iqn: "
"%s."
msgstr ""

#: cinder/volume/targets/tgt.py:327
msgid "Silent failure of target removal detected, retry...."
msgstr ""

#: cinder/zonemanager/utils.py:79
msgid "Driver didn't return connection info, can't add zone."
msgstr ""

#: cinder/zonemanager/utils.py:104
msgid "Driver didn't return connection info from terminate_connection call."
msgstr ""

